### ISSUE TITLE
Any chance this can proxy to different mysql instances on the same port?

### ISSUE THREAD

**Issue by cristiangrama** [passcod/docker-rproxy#1]
Looking for something like
```
mysql1 3306
mysql2 3306
```

And then be able to connect to either mysql container (without getting them load balanced) using the domain/host/container name and port.

Is this possible?

**Comment by passcod** [comment]
Sorry — this is extremely not maintained, and I haven't used Docker in over a year anyway. You can certainly fork this and try to implement it. In theory I'd say what you want is entirely within HAProxy's realm of possibility.
